# Generated by Django 3.2.9 on 2022-06-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
